import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedIOSStatusBarBlackWidget8.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget332.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget328.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget326.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget338.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget344.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget342.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget340.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget334.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedHeaderWidget8.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget330.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget346.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget336.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generated2widget7/generated/GeneratedWidget348.dart';

/* Frame 2.운동/추가/루틴/등록/선택
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Generated2Widget8'),
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedHeaderWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIOSStatusBarBlackWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 36.0,
                child: GeneratedWidget326(),
              ),
              Positioned(
                left: 16.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 40.0,
                child: GeneratedWidget328(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.04926108374384237;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget330(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.05178727774784483;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget332(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.05178727774784483;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget334(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.05178727774784483;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget336(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.05178731533106912;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget338(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.051787296539456976;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget340(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.051787296539456976;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget342(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.051787296539456976;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04533333333333334,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget344(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 318.0,
                top: 718.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 48.0,
                child: GeneratedWidget346(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.29679802955665024;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05333333333333334,
                        y: constraints.maxHeight * 0.2647783251231527,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget348(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
