import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget227.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedIOSStatusBarBlackWidget6.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget239.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget233.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget229.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget256.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget221.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget237.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget219.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget225.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget235.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget231.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedHeaderWidget6.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget223.dart';
import 'package:flutterapp/samsonapp/generatedwidget213/generated/GeneratedWidget241.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame 운동추가/루틴/생성/가슴/수정
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget213 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget6(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 16.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget219(),
            ),
            Positioned(
              left: 16.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 40.0,
              child: GeneratedWidget221(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.04926108374384237;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget223(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget225(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget227(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget229(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178731533106912;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget231(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget233(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget235(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget237(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 318.0,
              top: 718.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedWidget239(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.29679802955665024;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05333333333333334,
                      y: constraints.maxHeight * 0.2647783251231527,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget241(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: -20.0,
              top: -17.0,
              right: null,
              bottom: null,
              width: 412.0,
              height: 829.0,
              child: GeneratedRectangle46Widget(),
            ),
            Positioned(
              left: 7.0,
              top: 309.0,
              right: null,
              bottom: null,
              width: 362.0,
              height: 195.0,
              child: GeneratedWidget256(),
            )
          ]),
    ));
  }
}
