import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget188.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget186.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget178.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget194.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget184.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedHeaderWidget5.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedIOSStatusBarBlackWidget5.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget192.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget190.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget180.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget176.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget182.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget198.dart';
import 'package:flutterapp/samsonapp/generatedwidget170/generated/GeneratedWidget196.dart';

/* Frame 운동추가/루틴/생성/가슴
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget170 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget5(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget5(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 16.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget176(),
            ),
            Positioned(
              left: 16.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 40.0,
              child: GeneratedWidget178(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.04926108374384237;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget180(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget182(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget184(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget186(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178731533106912;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget188(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget190(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget192(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget194(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 318.0,
              top: 718.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedWidget196(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.29679802955665024;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05333333333333334,
                      y: constraints.maxHeight * 0.2647783251231527,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget198(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
