import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generated2widget6/generated/GeneratedWidget155.dart';
import 'package:flutterapp/samsonapp/generated2widget6/generated/GeneratedWidget138.dart';
import 'package:flutterapp/samsonapp/generated2widget6/generated/GeneratedHeaderWidget4.dart';
import 'package:flutterapp/samsonapp/generated2widget6/generated/GeneratedIOSStatusBarBlackWidget4.dart';
import 'package:flutterapp/samsonapp/generated2widget6/generated/GeneratedWidget136.dart';

/* Frame 2.운동/추가/전체
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget4(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 16.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget136(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178731533106912;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.037333333333333336,
                      y: constraints.maxHeight * 0.11945812807881774,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget138(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.29679802955665024;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.048,
                      y: constraints.maxHeight * 0.20320197044334976,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget155(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
