import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generateddaycheckwidget/generated/GeneratedTheDayWidget6.dart';
import 'package:flutterapp/samsonapp/generateddaycheckwidget/generated/GeneratedIconOWidget182.dart';
import 'package:flutterapp/samsonapp/generateddaycheckwidget/generated/GeneratedIconGWidget182.dart';
import 'package:flutterapp/samsonapp/generateddaycheckwidget/generated/Generated1Widget28.dart';
import 'package:flutterapp/samsonapp/generateddaycheckwidget/generated/GeneratedIconRWidget182.dart';

/* Component Day-check
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaycheckWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 35.0,
        height: 35.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 30.000001907348633,
                height: 30.0,
                child: GeneratedTheDayWidget6(),
              ),
              Positioned(
                left: 13.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 22.0,
                child: Generated1Widget28(),
              ),
              Positioned(
                left: 21.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedIconGWidget182(),
              ),
              Positioned(
                left: 15.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedIconOWidget182(),
              ),
              Positioned(
                left: 9.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedIconRWidget182(),
              )
            ]),
      ),
    ));
  }
}
