import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generated3widget13/generated/GeneratedContentBlocksWidget1.dart';
import 'package:flutterapp/samsonapp/generated3widget13/generated/GeneratedUnionWidget24.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generated3widget13/generated/GeneratedIOSStatusBarBlackWidget28.dart';
import 'package:flutterapp/samsonapp/generated3widget13/generated/GeneratedPageHeaderWidget14.dart';
import 'package:flutterapp/samsonapp/generated3widget13/generated/GeneratedIOSBottomBar5TabsWidget11.dart';
import 'package:flutterapp/samsonapp/generated3widget13/generated/GeneratedInputSearchWidget4.dart';

/* Frame 3.게시판
    Autogenerated by FlutLab FTF Generator
  */
class Generated3Widget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 44.0,
                      child: GeneratedIOSStatusBarBlackWidget28(),
                    ),
                    Positioned(
                      left: 3.0,
                      top: 142.0,
                      right: null,
                      bottom: null,
                      width: 372.0,
                      height: 464.0,
                      child: GeneratedContentBlocksWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.034666666666666665;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 13.0;

                        double percentHeight = 0.01600985221674877;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 13.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.9066666666666666,
                              translateY:
                                  constraints.maxHeight * 0.08620689655172414,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedUnionWidget24())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 60.0,
                      right: 16.0,
                      bottom: null,
                      width: null,
                      height: 36.0,
                      child: GeneratedPageHeaderWidget14(),
                    ),
                    Positioned(
                      left: 18.0,
                      top: 112.0,
                      right: 14.0,
                      bottom: null,
                      width: null,
                      height: 30.0,
                      child: GeneratedInputSearchWidget4(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: -0.5,
              width: null,
              height: 83.5,
              child: GeneratedIOSBottomBar5TabsWidget11(),
            )
          ]),
    ));
  }
}
