import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/Generated9Widget8.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedIOSStatusBarWhiteWidget8.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedWidget653.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedWidget652.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/samsonapp/generatedwidget649/generated/GeneratedGroup30Widget.dart';

/* Frame 임시
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget649 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -95.0,
                top: -3.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 119.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget8(),
              ),
              Positioned(
                left: 30.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 39.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 35.0,
                child: Generated9Widget8(),
              ),
              Positioned(
                left: null,
                top: 124.0,
                right: 73.0,
                bottom: null,
                width: 64.0,
                height: 24.0,
                child: GeneratedWidget652(),
              ),
              Positioned(
                left: null,
                top: 124.0,
                right: 4.0,
                bottom: null,
                width: 64.0,
                height: 24.0,
                child: GeneratedWidget653(),
              ),
              Positioned(
                left: 30.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 39.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 39.0,
                child: GeneratedGroup27Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 39.0,
                child: GeneratedGroup28Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 39.0,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 39.0,
                child: GeneratedGroup30Widget(),
              )
            ]),
      ),
    ));
  }
}
