import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedInputTextWidget2.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedInputTextWidget3.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedInputTextWidget5.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedPageHeaderWidget16.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedInputTextWidget4.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedIOSStatusBarBlackWidget30.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedForgotyourpasswordWidget1.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedIOSKeyboardLightAlphabeticWidget2.dart';
import 'package:flutterapp/samsonapp/generatedwidget647/generated/GeneratedButtonPrimaryWidget2.dart';

/* Frame 회원가입
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget647 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget30(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget16(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 194.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 260.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget4(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 342.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 305.0,
                width: 180.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 1.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedForgotyourpasswordWidget1()),
              ),
              Positioned(
                left: 15.0,
                top: 326.0,
                right: 17.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget5(),
              )
            ]),
      ),
    ));
  }
}
