import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generated4widget8/generated/GeneratedIOSBottomBar5TabsWidget7.dart';
import 'package:flutterapp/samsonapp/generated4widget8/generated/GeneratedRectangle46Widget2.dart';
import 'package:flutterapp/samsonapp/generated4widget8/generated/GeneratedIOSStatusBarWhiteWidget5.dart';
import 'package:flutterapp/samsonapp/generated4widget8/generated/GeneratedUnionWidget10.dart';
import 'package:flutterapp/samsonapp/generated4widget8/generated/GeneratedPageHeaderWidget7.dart';
import 'package:flutterapp/samsonapp/generated4widget8/generated/GeneratedCalendarWidget5.dart';
import 'package:flutterapp/samsonapp/generated4widget8/generated/GeneratedWidget613.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame 4.일정/새일정등록
    Autogenerated by FlutLab FTF Generator
  */
class Generated4Widget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 706.0,
                child: GeneratedCalendarWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.034666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 13.0;

                  double percentHeight = 0.01600985221674877;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 13.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.9066666666666666,
                        translateY: constraints.maxHeight * 0.08620689655172414,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedUnionWidget10())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget7(),
              ),
              Positioned(
                left: -20.0,
                top: -17.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 829.0,
                child: GeneratedRectangle46Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 379.0,
                child: GeneratedWidget613(),
              )
            ]),
      ),
    ));
  }
}
