import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget277.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget293.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget279.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget287.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget273.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget291.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedRectangle46Widget1.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget281.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget310.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget295.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget289.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget285.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedHeaderWidget7.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget275.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedWidget283.dart';
import 'package:flutterapp/samsonapp/generatedwidget267/generated/GeneratedIOSStatusBarBlackWidget7.dart';

/* Frame 운동추가/루틴/생성/가슴/수정
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget267 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget7(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget7(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 16.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget273(),
            ),
            Positioned(
              left: 16.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 40.0,
              child: GeneratedWidget275(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.04926108374384237;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget277(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget279(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget281(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget283(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178731533106912;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget285(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget287(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget289(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget291(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 318.0,
              top: 718.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedWidget293(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.29679802955665024;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05333333333333334,
                      y: constraints.maxHeight * 0.2647783251231527,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget295(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: -20.0,
              top: -17.0,
              right: null,
              bottom: null,
              width: 412.0,
              height: 829.0,
              child: GeneratedRectangle46Widget1(),
            ),
            Positioned(
              left: 7.0,
              top: 309.0,
              right: null,
              bottom: null,
              width: 362.0,
              height: 195.0,
              child: GeneratedWidget310(),
            )
          ]),
    ));
  }
}
