import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generated2widget11/generated/GeneratedHeaderWidget13.dart';
import 'package:flutterapp/samsonapp/generated2widget11/generated/GeneratedBoxWidget2.dart';
import 'package:flutterapp/samsonapp/generated2widget11/generated/GeneratedIOSStatusBarBlackWidget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generated2widget11/generated/GeneratedWidget492.dart';
import 'package:flutterapp/samsonapp/generated2widget11/generated/GeneratedWidget509.dart';

/* Frame 2.운동/추가/루틴/등록
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 16.0,
              top: 746.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget492(),
            ),
            Positioned(
              left: 18.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 375.0,
              child: GeneratedBoxWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget13(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget13(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 6.0,
              top: 290.0,
              right: null,
              bottom: null,
              width: 362.0,
              height: 275.0,
              child: GeneratedWidget509(),
            )
          ]),
    ));
  }
}
