import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget648/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/samsonapp/generatedwidget648/generated/GeneratedIOSStatusBarBlackWidget31.dart';
import 'package:flutterapp/samsonapp/generatedwidget648/generated/GeneratedButtonPrimaryWidget4.dart';
import 'package:flutterapp/samsonapp/generatedwidget648/generated/GeneratedButtonPrimaryWidget3.dart';

/* Frame 첫 페이지
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget648 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget31(),
              ),
              Positioned(
                left: 203.0,
                top: null,
                right: 29.0,
                bottom: 82.0,
                width: null,
                height: 55.0,
                child: GeneratedButtonPrimaryWidget3(),
              ),
              Positioned(
                left: 66.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 250.00001525878906,
                height: 65.0,
                child: GeneratedGroupWidget(),
              ),
              Positioned(
                left: 33.0,
                top: null,
                right: 199.0,
                bottom: 80.0,
                width: null,
                height: 55.0,
                child: GeneratedButtonPrimaryWidget4(),
              )
            ]),
      ),
    ));
  }
}
