import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget384.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget376.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedHeaderWidget9.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget378.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget370.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/Generated1Widget6.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget380.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget390.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget388.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget374.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget372.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget382.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedIOSStatusBarBlackWidget9.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedEllipse35Widget.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget386.dart';
import 'package:flutterapp/samsonapp/generated2widget8/generated/GeneratedWidget368.dart';

/* Frame 2.운동/추가/루틴/등록/선택
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget9(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 16.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget368(),
            ),
            Positioned(
              left: 16.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 40.0,
              child: GeneratedWidget370(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.04926108374384237;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget372(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget374(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget376(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget378(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178731533106912;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget380(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget382(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget384(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget386(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 318.0,
              top: 718.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedWidget388(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.29679802955665024;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05333333333333334,
                      y: constraints.maxHeight * 0.2647783251231527,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget390(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 350.0,
              top: 721.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedEllipse35Widget(),
            ),
            Positioned(
              left: 355.0,
              top: 726.0,
              right: null,
              bottom: null,
              width: 11.0,
              height: 11.0,
              child: Generated1Widget6(),
            )
          ]),
    ));
  }
}
