import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generateddayoriginalwidget/generated/Generated1Widget26.dart';
import 'package:flutterapp/samsonapp/generateddayoriginalwidget/generated/GeneratedIconRWidget180.dart';
import 'package:flutterapp/samsonapp/generateddayoriginalwidget/generated/GeneratedIconGWidget180.dart';
import 'package:flutterapp/samsonapp/generateddayoriginalwidget/generated/GeneratedIconOWidget180.dart';

/* Component Day-original
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDayoriginalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 35.0,
        height: 35.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 13.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 22.0,
                child: Generated1Widget26(),
              ),
              Positioned(
                left: 22.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedIconGWidget180(),
              ),
              Positioned(
                left: 16.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedIconOWidget180(),
              ),
              Positioned(
                left: 10.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedIconRWidget180(),
              )
            ]),
      ),
    ));
  }
}
