import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget646/generated/GeneratedPageHeaderWidget15.dart';
import 'package:flutterapp/samsonapp/generatedwidget646/generated/GeneratedInputTextWidget.dart';
import 'package:flutterapp/samsonapp/generatedwidget646/generated/GeneratedInputTextWidget1.dart';
import 'package:flutterapp/samsonapp/generatedwidget646/generated/GeneratedIOSKeyboardLightAlphabeticWidget1.dart';
import 'package:flutterapp/samsonapp/generatedwidget646/generated/GeneratedIOSStatusBarBlackWidget29.dart';
import 'package:flutterapp/samsonapp/generatedwidget646/generated/GeneratedForgotyourpasswordWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generatedwidget646/generated/GeneratedButtonPrimaryWidget1.dart';

/* Frame 로그인
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget646 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget29(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget15(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 194.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 350.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 313.0,
                width: 180.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 1.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedForgotyourpasswordWidget()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget1(),
              )
            ]),
      ),
    ));
  }
}
