import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generatedwidget472/generated/GeneratedWidget473.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generatedwidget472/generated/GeneratedBoxWidget1.dart';
import 'package:flutterapp/samsonapp/generatedwidget472/generated/GeneratedHeaderWidget12.dart';
import 'package:flutterapp/samsonapp/generatedwidget472/generated/GeneratedIOSStatusBarBlackWidget12.dart';

/* Frame 운동추가/루틴
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget472 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 16.0,
              top: 745.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget473(),
            ),
            Positioned(
              left: 18.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 452.0,
              child: GeneratedBoxWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget12(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget12(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
