import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget67.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget75.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget69.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget63.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget71.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget77.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget61.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedIOSStatusBarBlackWidget2.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget65.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget73.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget59.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget55.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedWidget57.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/samsonapp/generated2widget4/generated/GeneratedHeaderWidget2.dart';

/* Frame 2.운동/추가/루틴/등록/부위
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget2(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 16.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget55(),
            ),
            Positioned(
              left: 16.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 40.0,
              child: GeneratedWidget57(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.04926108374384237;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget59(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget61(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget63(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178727774784483;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget65(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.05178731533106912;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget67(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget69(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget71(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.051787296539456976;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04533333333333334,
                      y: constraints.maxHeight * 0.19088669950738915,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget73(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 318.0,
              top: 718.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedWidget75(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9146666666666666;

                final double height =
                    constraints.maxHeight * 0.29679802955665024;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05333333333333334,
                      y: constraints.maxHeight * 0.2647783251231527,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget77(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
