import 'package:flutter/material.dart';
import 'package:flutterapp/samsonapp/generated2widget2/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/samsonapp/generated2widget2/generated/Generated2Widget3.dart';
import 'package:flutterapp/samsonapp/generated2widget2/generated/GeneratedIOSStatusBarBlackWidget1.dart';
import 'package:flutterapp/samsonapp/generated2widget2/generated/GeneratedWidget32.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame 2.운동/추가/전체/리스트
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedHeaderWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.054187192118226604;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIOSStatusBarBlackWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 16.0,
              top: 748.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget32(),
            ),
            Positioned(
              left: 14.0,
              top: 97.0,
              right: null,
              bottom: null,
              width: 346.0,
              height: 410.0,
              child: Generated2Widget3(),
            )
          ]),
    ));
  }
}
